// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html ./BaseDijit jimu/utils jimu/dijit/Chart ../utils".split(" "),function(p,k,l,q,h,r,m){return p([q],{templateString:'\x3cdiv style\x3d"width:100%;height:100%;"\x3e\x3cdiv data-dojo-attach-point\x3d"noDataDiv"class\x3d"no-data-tip"\x3e${nls.noData}\x3c/div\x3e\x3cdiv class\x3d"gauge-dom" data-dojo-attach-point\x3d"gaugeDomNode"\x3e\x3c/div\x3e\x3c/div\x3e',type:"gauge",baseClass:"infographic-gauge-dijit",config:null,defValueStyle:{state:!0,isRatio:!1,
font:{font:{fontFamily:"Arial",bold:!1,italic:!1,underline:!1},textColor:"#59bad8"},dataFormat:{unit:"none",decimalPlaces:"",prefix:"",suffix:""}},constructor:function(a){this.visible=a.visible},postCreate:function(){this.inherited(arguments);this._features=[];this.setConfig(this.config);this._updateBackGroundColor()},setLayerInfo:function(){},setVisible:function(a){this.visible=a},onDataSourceDataUpdate:function(a){this.inSettingPage?a&&"undefined"!==typeof a.features&&(this._features=m.cleanFeatures(a.features)):
"number"===typeof a&&(this._value=a)},resize:function(){this.chart&&this.chart.resize()},setDataSource:function(a){this.inherited(arguments);this.dataSource=a},setConfig:function(a){a&&(this.config=a)},startRendering:function(){if(this._shouldRenderGauge())if(this.chart||this._createJimuChart(),this._updateBackGroundColor(),this._calculateGaugeValue(),"number"!==typeof this.gaugeValue)this.showNodata();else{var a=this._createChartOption();this.chart.updateConfig(a)}},_calculateGaugeValue:function(){var a;
a=this.inSettingPage?m.getValueFromFeatures(this.config&&this.config.statistic,this.dataSource,this._features):this._value;"undefined"!==typeof a&&!1!==a&&(this.gaugeValue=a)},_createChartOption:function(){var a=this.config,b={series:[{data:[this.gaugeValue]}]};b.shape=a.shape;b.type="gauge";b.theme=this.isDarkTheme()?"dark":"light";var c=this._createGaugeOption();b.gaugeOption=c;c=a.min||0;b.max=a.max||1E3;b.min=c;return b},_createGaugeOption:function(){var a=this.gaugeValue,b=this.config,c={},d=
this._getValueStyle();d&&(c.valueStyle=d);this._setGaugeDisplay(c);a=this._getIndicatorInfo(b,a);a.targetValue&&(b=this._isShowTargetValue(),c.targetValue=b?a.targetValue:[]);a.columnColor&&(c.columnColor=a.columnColor);return c},_getIndicatorInfo:function(a,b){var c=!1,d=!1,n=!1,f=this._getIndicatorValues(a);h.isNotEmptyObject(f,!0)&&(c=f);if(f=a.indicators)(a=m.getVaildIndicator(b,f,a.max))&&a.gaugeColor&&(d=a.gaugeColor),a&&a.valueColor&&(n=a.valueColor);return{targetValue:c,columnColor:d,valueColor:n}},
_getIndicatorValues:function(a){var b=[];a.indicators&&(a.indicators.forEach(function(c){c.value&&c.value.forEach(k.hitch(this,function(d){b.push(c.isRatio?d/100*a.max:d)}))}),b.sort(function(a,b){return a-b}),b=h.uniqueArray(b));return b},_shouldRenderGauge:function(){if(this.visible&&this.config){var a;(a=this.inSettingPage?this.domNode&&this._features:this.domNode&&"number"===typeof this._value)?this.hideNodata():this.showNodata();return!!a}},_updateBackGroundColor:function(){var a=this.config;
(a=a&&a.display&&a.display.backgroundColor)&&l.setStyle(this.domNode,"backgroundColor",a)},_createJimuChart:function(){var a=this._getDefaultChartOption();this.chart=new r({chartDom:this.gaugeDomNode,config:a});this.chart.placeAt(this.gaugeDomNode);this.chart.resize()},_generateValueFormatter:function(a){var b=this.config.max||1E3;if(a)return k.hitch(this,function(a,d){var c,f="",g,e=a.dataFormat;if(!e)return d;if((g=e.decimalPlaces)||0===g)g=Number(g);c=a.isRatio?h.convertNumberToPercentage(d/b,
g):d;a.isRatio||("percentage"===e.unit?c=h.convertNumberToPercentage(d,g):"thousand"===e.unit?(f=this.nls.thousandAbbreviation,c/=1E3):"million"===e.unit?(f=this.nls.millionAbbreviation,c/=1E6):"billion"===e.unit&&(f=this.nls.billionAbbreviation,c/=1E9));a.isRatio||"percentage"===e.unit||"number"!==typeof g||(c=c.toFixed(g));f&&(c+=f);a=c;e.prefix&&(a=e.prefix+" "+a);e.suffix&&(a+=" "+e.suffix);return a},a,this.gaugeValue)},_getVaildDecimalPlaces:function(a){if((a=(a=a.dataFormat)&&a.decimalPlaces)||
0===a)a=Number(a);if("number"===typeof a)return a},_getVaildValueDisplay:function(){var a=this.config;if(a=a&&a.display)return a.currentValue&&a.currentValue.state?a.currentValue:k.clone(this.defValueStyle)},_generateTextStyle:function(a){var b=this._getIndicatorInfo(this.config,this.gaugeValue),c=a&&a.font;if(c){a={};"undefined"!==typeof c.fontSize&&(a.fontSize=Number(c.fontSize));a.color=b.valueColor||c.textColor;b=c.font;if(!b)return a;a.fontWeight=b.bold?"bold":"normal";b.fontFamily&&(a.fontFamily=
b.fontFamily);a.fontStyle=b.italic?"italic":"normal";return a}},_isShowTargetValue:function(){var a=this.config&&this.config.display&&this.config.display.dataLabels;if(a)return!!a.targetValue},_setGaugeDisplay:function(a){var b=this.config.display;b&&(b.gaugeColor&&(a.columnColor=b.gaugeColor),b.bgColor&&(a.bgColor=b.bgColor),b.dataLabels&&b.dataLabels.state&&(b=b.dataLabels,a.showDataRangeLabel=!!b.dataRange,a.showTargetValueLabel=!!b.targetValue,a.labelColor=b.textColor||""))},_getValueStyle:function(){var a=
this._getVaildValueDisplay();if(a){var b={},c=this._getVaildDecimalPlaces(a);"number"===typeof c&&(b.decimalPlaces=c);b.formatter=this._generateValueFormatter(a);if(a=this._generateTextStyle(a))b.textStyle=a;return b}},_getDefaultChartOption:function(){var a={type:"gauge",confine:!0,shape:"curved",min:0,max:100,series:[{data:[0]}]};this.config&&this.config.shape&&(a.shape=this.config.shape);a.theme=this.isDarkTheme()?"dark":"light";return a},showNodata:function(a){this.chart&&this.chart.clear();l.addClass(this.domNode,
"no-data");a&&(this.noDataDiv.innerHTML=a)},hideNodata:function(){l.removeClass(this.domNode,"no-data")}})});