// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Deferred dojo/_base/lang dojo/promise/all esri/tasks/query esri/tasks/QueryTask jimu/LayerInfos/LayerInfos jimu/DataSourceManager jimu/utils ./utils".split(" "),function(h,g,d,k,l,m,n,p,q,e){return h([],{constructor:function(a){this.appConfig=a.appConfig;this.map=a.map;this.layerInfosObj=n.getInstanceSync();this.dataSourceManager=p.getInstance()},preprocessingDataSource:function(a){var b=this._tryGetLayerIdDataSchema(a),c=b.dataSchema,b=this._tryGetLayerObject(b.layerId),
c=this._tryGetLayerForFrameWork(c),f=this.getLayerDefinitionByDataSource(a);a=this.getFeaturesByDataSource(a);return k([b,c,f,a]).then(function(a){var b=a[0];return{layerObject:b&&b.layerObject,popupInfo:b&&b.popupInfo,featureLayerForFrameWork:a[1],definition:a[2],features:a[3]}})},_tryGetLayerIdDataSchema:function(a){var b={layerId:"",dataSchema:null};if(a.layerId)this.dsType="CLIENT_FEATURES",b.layerId=a.layerId;else if(a.frameWorkDsId){a=(a=e.getDsTypeInfoMeta(a.frameWorkDsId,this.appConfig))&&
a.dsMeta;if(!a)return b;"Features"===a.type?this.dsType="FRAMEWORK_FEATURES":"FeatureStatistics"===a.type&&(this.dsType="FRAMEWORK_STATISTICS");b.dataSchema=a.dataSchema;a=e.parseDataSourceId(a.id);b.layerId=a&&a.layerId}return b},_tryGetLayerObject:function(a){var b=new g;if(!a)return b.resolve(),b;var c=this.layerInfosObj.getLayerInfoById(a);c||(c=this.layerInfosObj.getTableInfoById(a));if(!c)return console.error("Invaild data source"),b.resolve(),b;var f=c.getPopupInfo();return c.getLayerObject().then(function(a){return{layerObject:a,
popupInfo:f}}.bind(this))},_tryGetLayerForFrameWork:function(a){var b=new g;if(!a)return b.resolve(),b;b=a;"FRAMEWORK_STATISTICS"===this.dsType&&(b=e.mockLayerDefinitionForSTD(a));return e.getLoadedLayer(b).then(function(a){return a}.bind(this))},getLayerDefinitionByDataSource:function(a){var b=new g;if(!a)return b.reject("Invaild data source"),b;if(a.layerId){var c=this.layerInfosObj.getLayerInfoById(a.layerId),f=c.getPopupInfo();c&&this._getServiceDefinitionByLayerInfo(c).then(function(a){this._addAliasForLayerDefinition(a,
f);b.resolve(a)}.bind(this))}else a.frameWorkDsId&&(c=null,a=(this.appConfig.dataSource&&this.appConfig.dataSource.dataSources)[a.frameWorkDsId],"Features"===a.type?(c=d.clone(a.dataSchema),this._addAliasForLayerDefinition(c),b.resolve(c)):"FeatureStatistics"===a.type&&(c={type:"Table",fields:[]},a=d.clone(a.dataSchema),c.fields=a.fields,a.groupByFields&&a.groupByFields[0]&&(c.groupByFields=d.clone(a.groupByFields)),this._addAliasForLayerDefinition(c),b.resolve(c)));return b},_getServiceDefinitionByLayerInfo:function(a){return a.getServiceDefinition().then(d.hitch(this,
function(b){return b?b:a.getLayerObject().then(d.hitch(this,function(a){return a?q.getFeatureLayerDefinition(a):null}))}))},_addAliasForLayerDefinition:function(a,b){a&&a.fields&&0<a.fields.length&&a.fields.forEach(d.hitch(this,function(a){var c=e.getFieldAliasByFieldInfo(a,b);c&&(a.alias=c)}))},getFeaturesByDataSource:function(a){return this._getFeaturesByDataSource(a).then(function(a){(a=a&&a.features)||(a=[]);a&&1E3<a.length&&(a=a.slice(0,1E3));return a}.bind(this),function(a){return a}.bind(this))},
_getFeaturesByDataSource:function(a){var b=new g;if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===a.dataSourceType){var c=this.layerInfosObj.getLayerInfoById(a.layerId);if(!c)return b.reject("Can not get layerInfo by the layer id of this data source."),b;a=c.getUrl();c=c.getFilter();if(!a)return b.reject("Invaild layer url of data source."),b;b=new l;b.outSpatialReference=this.map.spatialReference;b.where=c||"1\x3d1";b.outFields=["*"];b.returnGeometry=!1;return(new m(a)).execute(b)}if("DATA_SOURCE_FROM_FRAMEWORK"===
a.dataSourceType){a=this.dataSourceManager.getDataSourceConfig(a.frameWorkDsId);if(!a)return b.reject("Can not get vaild data source config by the frameWorkDsId of this data source."),b;a.filterByExtent=!1;return this.dataSourceManager.doQuery(a)}}})});