// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on jimu/utils jimu/DataSourceManager jimu/statisticsUtils dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/Deferred esri/layers/FeatureLayer".split(" "),function(k,h,r,t,g,n,l,u,p){return{getClientFeaturesFromMap:function(a,b,c,d){return h.getClientFeaturesFromMap(a,b,c,d)},listenClientFeaturesFromMap:function(a,b,c,d,e){var f=[];c&&(f.push(k(b,"selection-complete",g.hitch(this,function(){e(this.getClientFeaturesFromMap(a,b,c,d))}))),f.push(k(b,"selection-clear",g.hitch(this,function(){e(this.getClientFeaturesFromMap(a,
b,c,d))}))));d&&f.push(k(a,"extent-change",g.hitch(this,function(){0<b.graphics.length&&e(this.getClientFeaturesFromMap(a,b,c,d))})));f.push(k(b,"update-end",g.hitch(this,function(){e(this.getClientFeaturesFromMap(a,b,c,d))})));e(this.getClientFeaturesFromMap(a,b,c,d));return{remove:function(){f&&l.forEach(f,g.hitch(this,function(a){a.remove()}));f=null}}},getVaildIndicator:function(a,b,c){var d=[];b.map(g.hitch(this,function(b){(b=this._handleOperator(b,a,c))&&d.push(b)}));if(0<d.length)return d[d.length-
1]},getSingleValueFromFeatures:function(a,b,c){if(!c||!c.length)return null;var d=r.getInstance(),e=0;if("Features"===a.type){if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===b.dataSourceType||"Features"===d.getDataSourceConfig(b.frameWorkDsId).type)return c.length;e=0;l.forEach(c,function(a){var b=a.attributes.STAT_COUNT;"undefined"===typeof b&&(b=a.attributes.stat_count);e+=b});return e}if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===b.dataSourceType||"Features"===d.getDataSourceConfig(b.frameWorkDsId).type)return this._getStatsFromFeatures(c,
a.fieldName,a.statisticsType);var f=0,q=0,e=0,g=h.upperCaseString(a.fieldName+"_"+a.statisticsType);l.forEach(c,function(b){var c=b.attributes[g];"undefined"===typeof c&&(g=h.lowerCaseString(a.fieldName+"_"+a.statisticsType),c=b.attributes[g]);switch(a.statisticsType){case "sum":f+=c;break;case "min":f=Math.min(f,c);break;case "max":f=Math.max(f,c);break;case "avg":b=this._getSumCountValue(a.fieldName,b.attributes),q+=b.sum,e+=b.count}}.bind(this));"avg"===a.statisticsType&&(f=0===e?0:q/e);return f},
_getSumCountValue:function(a,b){var c;c=h.upperCaseString(a+"_SUM");c=b[c];"undefined"===typeof c&&(c=h.lowerCaseString(a+"_SUM"),c=b[c]);a=b.STAT_COUNT;"undefined"===typeof a&&(a=h.lowerCaseString("STAT_COUNT"),a=b[a]);return{sum:c||0,count:a||0}},filterFeaturesByDataSourceSetting:function(a,b,c){if(0===a.length)return[];if(b.useSelection){var d=a[0].getLayer();if(d){var e=d.getSelectedFeatures();0<e.length&&(a=l.filter(a,function(a){return-1<e.indexOf(a)}))}}b.filterByExtent&&(a=h.filterFeaturesByExtent(c.extent,
a));return a},_getStatsFromFeatures:function(a,b,c){return t.getStatisticsResultFromClientSync({featureSet:{features:a},fieldName:b,statisticTypes:[c]})[c+"Field"]},_handleOperator:function(a,b,c){function d(a){e={};a.valueColor&&(e.valueColor=a.valueColor);a.gaugeColor&&(e.gaugeColor=a.gaugeColor);a.iconInfo&&(e.iconInfo=a.iconInfo)}var e,f=a.value.map(g.hitch(this,function(b){return a.isRatio?b/100*c:b}));"greater"===a.operator&&b>f[0]?d(a):"smaller"===a.operator&&b<f[0]?d(a):"between"===a.operator&&
b>f[0]&&b<f[1]?d(a):"equal"===a.operator&&b===f[0]?d(a):"notEqual"===a.operator&&b!==f[0]&&d(a);return e},isInteger:function(a){return"number"===typeof a&&0===a%1},checkDataSourceIsVaild:function(a,b,c,d){var e={code:0,fields:[]},f=null;a?"DATA_SOURCE_FROM_FRAMEWORK"===a.dataSourceType?d&&d.dataSource&&d.dataSource.dataSources?(c=d.dataSource.dataSources[a.frameWorkDsId])?(f=c.dataSchema&&c.dataSchema.fields,e=this._isDataSourceContainNeededFields(f,b,e)):e.code=1:e.code=1:"DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===
a.dataSourceType&&((a=a.layerId)&&c?(c=c.getLayer(a))?(f=c.fields,e=this._isDataSourceContainNeededFields(f,b,e)):e.code=1:e.code=1):e.code=1;return e},_isDataSourceContainNeededFields:function(a,b,c){if(!a||!a.length)return c.code=1,c;var d=this._getFieldNamesByFields(a);a=this._getNeededFieldsByMainDijitJson(b);if(!a||!a.length)return c.code=0,c;a.forEach(function(a){0>d.indexOf(a)&&c.fields.push(a)});c.fields.length&&(c.code=2);return c},_getNeededFieldsByMainDijitJson:function(a){if(a)return this._getNeededFieldsByDijitConfig(a.type,
a.config)},_getNeededFieldsByDijitConfig:function(a,b){var c=null;if(b){if("chart"===a)c=[],b.labelField&&c.push(b.labelField),b.categoryField&&c.push(b.categoryField),b.valueFields&&b.valueFields.length&&(c=c.concat(b.valueFields));else if("gauge"===a||"number"===a)c=[],(a=b.statistic)&&(a=a.fieldName)&&c.push(a);if(c&&c.length)return c}},_getFieldNamesByFields:function(a){if(a&&a.length)return a.map(function(a){return this._getFieldNameByFieldInfo(a)}.bind(this))},_getFieldNameByFieldInfo:function(a){return a&&
a.name},isBaseAxisChart:function(a){return"column"===a||"bar"===a||"line"===a},isEqual:function(a,b){return typeof a!==typeof b?!1:"object"!==typeof a?a===b:h.isEqual(a,b)},separationChartProperties:function(a){var b=a.type;a=a.mode;var c=["mode","type"],d=["backgroundColor","seriesStyle","legend","highLightColor"];"feature"===a?c=c.concat(["labelField","valueFields"]):"category"===a?c=c.concat(["categoryField","dateConfig","valueFields","operation","nullValue"]):"count"===a?c=c.concat(["categoryField",
"dateConfig"]):"field"===a&&(c=c.concat(["valueFields","operation","nullValue"]));c=c.concat(["sortOrder","maxLabels"]);d="pie"===b?d.concat(["dataLabel","innerRadius"]):d.concat(["xAxis","yAxis","stack","area","marks"]);return{dataProperties:c,displayProperties:d}},classifyChartConfig:function(a){if(a){var b=this.separationChartProperties(a),c=b.displayProperties,d={},e={};b.dataProperties.forEach(g.hitch(this,function(b){d[b]=a[b]}));c.forEach(g.hitch(this,function(b){e[b]=a[b]}));return{data:d,
display:e}}},getCleanChartConfig:function(a){var b={mode:a.mode,type:a.type},c=this.separationChartProperties(a),d=c&&c.dataProperties,c=c&&c.displayProperties;d&&d.length&&d.forEach(g.hitch(this,function(c){b[c]=a[c]}));c&&c.length&&c.forEach(g.hitch(this,function(c){b[c]=a[c]}));return!b.mode||!("count"===b.mode||b.valueFields&&b.valueFields.length)||"pie"===b.type&&""===b.maxLabels?null:g.clone(b)},_cloneAndFormatDS:function(a){a=g.clone(a);var b={};a.name&&(b.name=a.name);a.dataSourceType&&(b.dataSourceType=
a.dataSourceType);a.layerId&&(b.layerId=a.layerId);a.frameWorkDsId&&(b.frameWorkDsId=a.frameWorkDsId);a=null;return b},isDSEqual:function(a,b){if(a&&b)return a=this._cloneAndFormatDS(a),b=this._cloneAndFormatDS(b),this.isEqual(a,b)},separationGradientColors:function(a,b){var c=[];2===a.length&&(c=this._createGradientColors(a[0],a[a.length-1],b));return c},_createGradientColors:function(a,b,c){var d=[];a=new n(a);var e=new n(b);b=(e.r-a.r)/c;for(var f=(e.g-a.g)/c,e=(e.b-a.b)/c,g=new n,h=0,k=0,l=0,
m=0;m<c;m++)h=parseInt(a.r+b*m,10),k=parseInt(a.g+f*m,10),l=parseInt(a.b+e*m,10),g.setColor([h,k,l]),d.push(g.toHex());return d},mockLayerDefinitionForSTD:function(a){var b={type:"Table",fields:[]};b.fields=a.fields;b.fields.push({name:"STAT_COUNT",type:"esriFieldTypeInteger",alias:"STAT_COUNT"});return b},getLoadedLayer:function(a){var b=new u,c=null,c="string"===typeof a?new p(a):"esri.layers.FeatureLayer"===a.declaredClass?a:new p({layerDefinition:g.clone(a),featureSet:null});if(c.loaded)b.resolve(c);
else c.on("load",function(){b.resolve(c)});return b},parseDataSourceId:function(a){var b=a.split("~"),c={};if(2>b.length)return console.error("Bad data source id:",a),c;switch(b[0]){case "map":return b=a.lastIndexOf("~"),c={from:"map",layerId:a.substring(4,b)};case "widget":return c={from:"widget",widgetId:b[1]};case "external":return c={from:"external"};default:console.error("Bad data source id:",a)}},getDsTypeInfoMeta:function(a,b){var c={dsTypeInfo:null,dsMeta:null};c.dsTypeInfo=this.parseDataSourceId(a);
if(b=b.dataSource&&b.dataSource.dataSources)c.dsMeta=b[a];return c},getValueFromFeatures:function(a,b,c){if(!a||!b||!c)return!1;a=this.getSingleValueFromFeatures(a,b,c);a=this._getVaildValue(a);return"number"!==typeof a?!1:a},_getVaildValue:function(a){if(a||0===a)return Number(a)},cleanFeatures:function(a){if(a&&a.length)return a.map(function(a){return{attributes:a.attributes}})},getFieldAliasByFieldInfo:function(a,b){var c="";if(!a)return c;var d=a.name,c=a.alias||d;b&&(c=this.getAliasFromPopupInfo(d,
b));return c},getAliasFromPopupInfo:function(a,b){var c=a;if(!b)return c;(b=b.fieldInfos)&&0<b.length&&b.forEach(function(b){b.fieldName===a&&(c=b.label)});return c}}});