// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/declare","dojo/_base/lang","jimu/utils","../../utils"],function(v,h,q,g){return v(null,{oidFieldType:"esriFieldTypeOID",stringFieldType:"esriFieldTypeString",numberFieldTypes:["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],_customColorDefaultNum:5,dateFieldType:"esriFieldTypeDate",constructor:function(a){a&&h.mixin(this,a);this.others=[{text:this.nls.nullText,label:this.nls.nullText,id:"null",color:"#808080"},{text:this.nls.others,
label:this.nls.others,id:"others",color:"#808080"}];this.colors&&(this.customColors=h.clone(this.colors))},setDataSource:function(a){a&&(this.dataSource=a)},setLayerDefinition:function(a){a&&(this.definition=a)},setPreModle:function(a){this.PRE_MODLE=a},setCustomColor:function(a){this.customColors=h.clone(a)},setFeatures:function(a){this.features=a},getInitializationModle:function(a){return h.clone({config:a,computed:{sortComputed:null,definition:null,showDateOption:"",showUseLayerSymbology:!1,valueFieldsAsMultipleMode:!0,
seriesStyleComputed:null,legendDisplay:!0}})},getInitConfig:function(a,b,c){a=this._getInitDataConfig(a,b&&b.type,c);b=this._getInitDisplayConfig(b);return h.mixin(a,b)},getRandomCustomColor:function(){var a;a=0;if(this._lastCustomColor){var b=this.customColors.indexOf(this._lastCustomColor);-1<b&&(a=b+1,a>this.customColors.length-1&&(a=0))}return this._lastCustomColor=a=this.customColors[a]},updateModleComputed:function(a){var b=a.computed,c=a.config;b.sortComputed=this._calcuteSortComputed(a);b.showUseLayerSymbology=
this._shouldShowUseLayerSymbolDisplay(a);b.showDateOption=this._shouldShowDateOption(a);b.seriesStyleComputed=this._calcuteSeriesStyleComputed(a);b.valueFieldsAsMultipleMode=this._calcuteValueFieldsMode(c);b.legendDisplay=this._calcuteLegendDisplay(c)},dynamicUpdateConfig:function(a,b){var c=a.config;a=a.computed;this._dynamicUpdateDateConfig(c,a);this._dynamicUpdateSeriesStyle(c,a,b)},hasNumberFields:function(a){var b=!1;(a=a.fields)&&0<a.length&&(b=a.some(h.hitch(this,function(a){return 0<=this.numberFieldTypes.indexOf(a.type)})));
return b},getClusterFieldOptions:function(a,b){var c=[this.stringFieldType,this.dateFieldType,this.oidFieldType],c=c.concat(h.clone(this.numberFieldTypes));a=a.filter(h.hitch(this,function(a){return 0<=c.indexOf(a.type)})).map(h.hitch(this,function(a){return{label:a.alias||a.name,value:a.name}}));b&&(a=a.filter(function(a){return a.value===b}));return a},getValueFieldOptions:function(a,b,c){a=a.filter(h.hitch(this,function(a){return 0<=this.numberFieldTypes.indexOf(a.type)}));if(b&&c){var d=c.map(function(a){return a.value});
a=a.filter(function(a){return 0>d.indexOf(a.name)})}return a},isDSEqual:function(a,b){if(a&&b)return a=this._cloneAndFormatDS(a),b=this._cloneAndFormatDS(b),g.isEqual(a,b)},_calcuteSortComputed:function(a){var b={},c=a.config,d=c.sortOrder,c=c.mode,f=this.PRE_MODLE.config.mode;b.mode=c;a=this._getSortFields(a);b.fieldOption=a;!g.isEqual(c,f)&&f?b.sortArrowPosition="feature"===c?"down":"top":b.sortArrowPosition="feature"===c?"down":d.isLabelAxis?"top":"mid";return b},_shouldShowUseLayerSymbolDisplay:function(a){var b=
this.definition,c=!1,d=a.config.mode;if("line"===a.config.type||"field"===d)return c;var f,l=null,e=null;this.dataSource&&(e=this.dataSource,e.layerId?f=e.layerId:e.frameWorkDsId&&(e=g.parseDataSourceId(e.frameWorkDsId))&&"undefined"!==e.layerId&&(f=e.layerId));f&&(l=this._getFeatureLayer(f));if(!f)return c;if("feature"===d)c=!0;else if("category"===d||"count"===d){a=a.config.categoryField;if(!l)return c;l.renderer&&(l=l.renderer,"esri.renderer.ClassBreaksRenderer"===l.declaredClass||"esri.renderer.UniqueValueRenderer"===
l.declaredClass)&&(l.attributeField!==a||g.isDateField(a,b)||(c=!0))}return c},_shouldShowDateOption:function(a){var b=g.isDateField(a.config.categoryField,this.definition);a=a.config.mode;return("category"===a||"count"===a)&&b},_calcuteValueFieldsMode:function(a){var b=a.mode,c=!0;("feature"===b||"category"===b)&&a&&"pie"===a.type&&(c=!1);!c&&a.valueFields&&1<a.valueFields.length&&(a.valueFields=a.valueFields.slice(0,1));return c},_calcuteLegendDisplay:function(a){var b=a.mode,c;"pie"===a.type?c=
!0:(c=!0,"count"===b||"field"===b?c=!1:a.seriesStyle&&(c="layerSymbol"!==a.seriesStyle.type));return c},_calcuteSeriesStyleComputed:function(a){var b=a.config,c=b.mode,d=b.type,f=b.area,l=b.valueFields||[],e=b.categoryField,h=this.definition,m={},k="single",r=!0,n="none",k=[];a.computed.showUseLayerSymbology&&k.push("layerSymbol");"pie"!==d||"category"!==c&&"count"!==c||g.isDateField(e,h)||k.push("custom");2===k.length&&(n="all");1===k.length&&(n=k[0]);k=1<l.length?"multiply":"single";"line"===d&&
"field"===c&&(k="single");"pie"===d&&(r="field"===c);a="";if("category"===c||"count"===c)a=b.categoryField;m.colorSingleMode=r;m.colorDisplayMode=k;m.showOpacity=!!f;m.otherRadio=n;m.categoryField=a;if("custom"===n||"all"===n)b=g.isNumberType(e,h,!0),e=g.isContainCodedValuesField(e,h),m.categoryTypes={isNumberType:b,isCodedValueType:e},m.customColorSelects=this._getCustomColorSelects(a,h);m.chartType=d;return m},_createSeriesStyle:function(a,b,c){a={name:a,style:{color:this._getRandomColor()}};b&&
(a.style.opacity=6);c&&(a.style.color="#68D2E0 #087E92 #47BCF5 #FBE66A #F29157 #C8501D".split(" "));return a},_dynamicUpdateDateConfig:function(a,b){b.showDateOption?a.dateConfig||(a.dateConfig={isNeedFilled:!0,minPeriod:"automatic"}):a.dateConfig=null},_dynamicUpdateSeriesStyle:function(a,b,c){var d=a.mode,f=a.type,l=a.area,e=a.categoryField,u=a.valueFields||[],m=this.definition,k=h.clone(a.seriesStyle);k||(k={});var r=!1;"line"===f&&l&&(r=!0);b=b.showUseLayerSymbology;"undefined"===typeof k.type&&
(k.type="series");b||"layerSymbol"!==k.type||(k.type="series");"field"===d&&(k.type="series");"feature"===d&&"custom"===k.type&&(k.type="series");e&&g.isDateField(e,m)&&"custom"===k.type&&(k.type="series");var e=k.styles||[],n=[],p=[];b=[];n=e.map(function(a){return a.name});p=n.filter(function(a){return 0>u.indexOf(a)});b=u.filter(function(a){return 0>n.indexOf(a)});var q=!1;"column"===f||"bar"===f||"line"===f?"line"===f&&"field"===d?"line~field"===n[0]?(p=[],b=[]):(p=n,b=["line~field"]):"count"===
d&&("count~count"===n[0]?(p=[],b=[]):(p=n,b=["count~count"])):"pie"===f&&"field"!==d&&("pie~not-field"===n[0]?(p=[],b=[]):(q=!0,p=n,b=["pie~not-field"]));e=e.filter(function(a){return 0>p.indexOf(a.name)});d=b.map(function(a){return this._createSeriesStyle(a,r,q)}.bind(this));e=e.concat(d);k.styles=null;k.styles=e;e.forEach(function(a){-1<u.indexOf(a.name)?a.label=g.getFieldAlias(a.name,m,this.popupInfo):a.label=a.name}.bind(this));this._dynamicUpdateSeriesStyleCustomColor(k,a,c)},_dynamicUpdateSeriesStyleCustomColor:function(a,
b,c){var d=this.dataSource,f=this.definition,l=b.categoryField,e=this.PRE_MODLE.config;c="pie"!==b.type||"category"!==b.mode&&"count"!==b.mode?"remove":a.customColor?c?"keep":l===e.categoryField?"keep":"update":"update";e=null;"remove"===c?"undefined"!==typeof a.customColor&&delete a.customColor:"update"===c&&d&&l&&(e=this._getCustomColorCategories(l,f),a.customColor||(a.customColor={}),e&&(a.customColor.categories=e),a.customColor.others&&a.customColor.others.length||(a.customColor.others=h.clone(this.others)));
b&&(b.seriesStyle=a)},_getCustomColorSelects:function(a,b){var c=this._getCategoriesByFeatures(a);if(c&&c.length){var c=c.filter(function(a){return!!a||0===a}),d=[];g.isContainCodedValuesField(a,b)?(a=q.getCodedValueListForCodedValueOrSubTypes(b,a),d=h.clone(a)):d=c.map(function(a){return{label:a,value:a}});return d}},_getCustomColorCategories:function(a,b){var c=this._getCategoriesByFeatures(a);if(c&&c.length){c=c.filter(function(a){return!!a||0===a});c.length>this._customColorDefaultNum&&(c=c.slice(0,
this._customColorDefaultNum));var d=[];return d=g.isContainCodedValuesField(a,b)?c.map(function(c){var d=c;c=this._getDominDisplayValue(a,c,b);return{id:d,text:c,label:c,color:this.getRandomCustomColor()}}.bind(this)):c.map(function(a){return{id:a,text:a,label:a,color:this.getRandomCustomColor()}}.bind(this))}},_getCategoriesByFeatures:function(a){var b=[];if(!this.features||!this.features.length)return b;this.features.forEach(h.hitch(this,function(c){c=c.attributes[a];0>b.indexOf(c)&&b.push(c)}));
return this._sortOrderCategories(b)},_getSortFields:function(a){if(a){var b=this.definition;a=a.config;var c=a.mode;if(b&&a&&("feature"===c||a.valueFields&&a.valueFields[0])){var d=[];"feature"===c?(d=h.clone(b.fields),d=g.getNotGeometryFields(d)):a.valueFields&&(d=g.getFieldInfosByFieldName(a.valueFields,this.definition));return d.map(function(a){return{value:a.name,label:a.alias||a.name}})}}},_cloneAndFormatDS:function(a){a=h.clone(a);var b={};a.name&&(b.name=a.name);a.dataSourceType&&(b.dataSourceType=
a.dataSourceType);a.layerId&&(b.layerId=a.layerId);a.frameWorkDsId&&(b.frameWorkDsId=a.frameWorkDsId);a=null;return b},_sortOrderCategories:function(a){Array.isArray(a)&&a.sort(function(a,c){"string"===typeof s&&(a=a.toLowerCase());"string"===typeof t&&(c=c.toLowerCase());q.isNumberOrNumberString(a)&&(a=Number(a));q.isNumberOrNumberString(c)&&(c=Number(c));return a<c?-1:a>c?1:0}.bind(this));return a},_getDominDisplayValue:function(a,b,c){var d=b;(a=g.getFieldInfo(a,c))&&a.domain&&(a=a.domain.codedValues)&&
0<a.length&&a.some(function(a){return a.code===b?(d=a.name,!0):!1});return d},_getRandomColor:function(){var a;a=0;if(this._lastColor){var b=this.colors.indexOf(this._lastColor);-1<b&&(a=b+1,a>this.colors.length-1&&(a=0))}return this._lastColor=a=this.colors[a]},_getFeatureLayer:function(a){var b=null;this.map&&"undefined"!==typeof a&&(b=this.map.getLayer(a));return b},_getInitDisplayConfig:function(a){var b,c,d,f;a&&(b=a.type,c=a.area,d=a.stack,f=a.innerRadius);a=this.getDefaultColorOfTheme();var l=
a.textColor,e=a.bgColor,g={};a=["backgroundColor","seriesStyle","legend","highLightColor"];switch(b){case "column":case "bar":case "line":a=a.concat(["xAxis","yAxis","stack","area","marks"]);break;case "pie":a=a.concat(["dataLabel","innerRadius"])}var m={color:l,fontSize:12};a.forEach(function(a){switch(a){case "backgroundColor":g.backgroundColor=e;break;case "seriesStyle":g.seriesStyle={styles:[]};break;case "legend":g.legend={show:!1,textStyle:h.clone(m)};break;case "highLightColor":g.highLightColor=
void 0;break;case "xAxis":g.xAxis={show:!0,textStyle:h.clone(m),nameTextStyle:{color:l}};break;case "yAxis":g.yAxis={show:!0,textStyle:h.clone(m),nameTextStyle:{color:l}};break;case "dataLabel":g.dataLabel={show:!1,textStyle:h.clone(m)};break;case "innerRadius":g.innerRadius=f;break;case "stack":g.stack=d;break;case "area":g.area=c;break;case "marks":g.marks={}}}.bind(this));return g},_getInitDataConfig:function(a,b,c){var d={mode:a,type:b},f=["sortOrder","maxLabels"];switch(a){case "feature":f.push("labelField",
"valueFields");break;case "count":f.push("categoryField");break;case "category":f.push("categoryField","valueFields","operation","nullValue");break;case "field":f=f.concat(["operation","nullValue","valueFields"])}"category"!==a&&"count"!==a||!g.isDateField(c,this.definition)||f.push("dateConfig");f.forEach(function(f){switch(f){case "labelField":d.labelField=c;break;case "categoryField":d.categoryField=c;break;case "valueFields":d.valueFields=[];break;case "sortOrder":d.sortOrder=this._getInitSortOrderByMode(a);
break;case "operation":d.operation="sum";break;case "nullValue":d.nullValue=!0;break;case "dateConfig":d.dateConfig=this._getInitDateConfigByType(b);break;case "maxLabels":d.maxLabels="pie"===b?100:""}}.bind(this));return d},_getInitDateConfigByType:function(a){},_getInitSortOrderByMode:function(a){var b={isAsc:!0};"feature"===a?(a=this._getFieldsByDefinition())&&a[0]&&(b.field=a[0].value):b.isLabelAxis=!0;return b},_getFieldsByDefinition:function(a){if(a=a||this.definition)return h.clone(a.fields)},
getDefaultColorOfTheme:function(){var a={bgColor:"#fff",textColor:"#000"};if(!this.appConfig)return a;"DashboardTheme"!==this.appConfig.theme.name||"default"!==this.appConfig.theme.styles[0]&&"style3"!==this.appConfig.theme.styles[0]?"DartTheme"===this.appConfig.theme.name&&(a.bgColor="#4c4c4c",a.textColor="#fff"):(a.bgColor="#222222",a.textColor="#fff");return a}})});