// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/on dojo/string dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/_base/array dojo/dom-construct esri/graphic jimu/dijit/Message dijit/_WidgetBase ./presetUtils dojo/query esri/tasks/RelationshipQuery dojo/dom-geometry dojo/dom-class".split(" "),function(r,t,n,u,h,p,g,m,k,v,q,w,x,f,y,z,l){return r([w,t],{newRelatedFeature:{},isSaveEnable:!1,postCreate:function(){this._createTable()},_createTable:function(){var b;b=k.create("div",{"class":"relatedTablesContainer"},
this.domNode);m.forEach(this.relationshipInfo,g.hitch(this,function(c){c.featureLayer&&c.hasOwnProperty("relationshipId")&&this._createRelatedTableItem(c,b)}))},_createRelatedTableItem:function(b,c){var a,d,e;d=this.layerInfosObj.getLayerOrTableInfoById(b.featureLayer.id);a=k.create("div",{"class":"relatedTableTitleContainer"},c);h.set(a,"layerId",d.id);h.set(a,"relationshipId",b.relationshipId);h.set(a,"parentFeatureOID",this.parentFeature.attributes[this.parentFeature._layer.objectIdField]);n(a,
"click",g.hitch(this,function(a){a=h.get(a.currentTarget,"relatedRecordCount");(null===a||a&&0!==parseInt(a,10))&&this.emit("titleClicked",d.id,b.relationshipId,!1,this.parentFeatureIndexInAI,this.parentFeature.attributes[this.parentFeature._layer.objectIdField],this.newRelatedFeature[b.relationshipId].foreignKeyField)}));k.create("div",{"class":"relatedTableTitle esriCTEllipsis",innerHTML:d.title,title:d.title},a);k.create("div",{"class":"esriCTLoadingIcon hidden"},a);k.create("div",{"class":"esriCTRelatedTableRecordsCount"},
a);this._createNewGraphics(b.relationshipId,d.id);this._canAddFeatures(b,d)&&"Table"===d.layerObject.type&&(c=k.create("div",{"class":"relatedTableIcons itemTitleCreateNew",title:this.nls.addNewFeature},a),h.set(c,"tableId",d.id),n(c,"click",g.hitch(this,function(c){c.stopPropagation();e=this.newRelatedFeature[b.relationshipId];this.isSaveEnable?q({message:this.nls.pendingFeatureSaveMsg}):void 0===this.parentFeature.attributes[e.primaryKeyField]||null===this.parentFeature.attributes[e.primaryKeyField]?
(c=x.getFieldInfoByFieldName(this.parentFieldInfos,e.primaryKeyField).label||e.primaryKeyField,c=u.substitute(this.nls.invalidRelationShipMsg,{parentKeyField:c}),q({message:c})):(this.newRelatedFeature[b.relationshipId].attributes[this.newRelatedFeature[b.relationshipId].foreignKeyField]=this.parentFeature.attributes[this.newRelatedFeature[b.relationshipId].primaryKeyField],this.emit("addRelatedRecord",this.newRelatedFeature[b.relationshipId],a,d.id,this.parentFeatureIndexInAI,this.newRelatedFeature[b.relationshipId].foreignKeyField))})));
this.getRelatedRecordsCount(b.relationshipId,d.id)},_canAddFeatures:function(b,c){c=c.layerObject.getEditCapabilities();return!b.allowUpdateOnly&&b._editFlag&&c.canCreate?!0:!1},_createNewGraphics:function(b,c){var a,d,e;a={};c=this.layerInfosObj.getLayerOrTableInfoById(c);0<c.layerObject.templates.length?a=c.layerObject.templates[0].prototype.attributes:0<c.layerObject.types.length&&(a=c.layerObject.types[0].templates[0].prototype.attributes);a=new v(null,null,g.clone(a));d=this._getRelationShipById(this.parentFeature._layer,
b);e=this._getRelationShipById(c.layerObject,b);d=d.keyField;e=e.keyField;a.attributes.hasOwnProperty(e)&&(a.attributes[e]=this.parentFeature.attributes[d]);this.newRelatedFeature[b]=a;this.newRelatedFeature[b].primaryKeyField=d;this.newRelatedFeature[b].foreignKeyField=e;this.newRelatedFeature[b].featureLayer=c},_getRelationShipById:function(b,c){var a;m.some(b.relationships,g.hitch(this,function(b){if(b.id===c)return a=b,!0}));return a},updateFeatureInstance:function(b){this.parentFeature&&(this.parentFeature.attributes=
g.clone(b))},displayRelatedRecordCount:function(b,c){var a,d,e;c=f("[relationshipid \x3d "+c+"]",this.domNode);e=f(".relatedTableIcons.itemTitleCreateNew",this.domNode);d=f(".esriCTLoadingIcon",c[0])[0];l.add(d,"hidden");a=f(".esriCTRelatedTableRecordsCount",c[0])[0];l.remove(a,"hidden");d=f(".relatedTableTitle",c[0])[0];h.set(a,"innerHTML","("+b+")");h.set(c[0],"relatedRecordCount",b);a=z.position(a).w;if("auto"===a||void 0===a||""===a||0===a)a=8+7*b.toString().length;a=0<e.length?a+35:a+10;p.set(d,
"width","calc(100% - "+a+"px)");0===b?l.add(c[0],"esriCTRelatedTableTitleDefaultCursor"):l.remove(c[0],"esriCTRelatedTableTitleDefaultCursor")},updateRelatedRecordsCount:function(){m.forEach(this.relationshipInfo,g.hitch(this,function(b){this.getRelatedRecordsCount(b.relationshipId,b.featureLayer.id)}))},_showLoadingIndicator:function(b){var c,a,d;a=f("[relationshipid \x3d "+b+"]",this.domNode);b=f(".relatedTableIcons.itemTitleCreateNew",this.domNode);d=f(".esriCTLoadingIcon",a[0])[0];c=f(".esriCTRelatedTableRecordsCount",
a[0])[0];a=f(".relatedTableTitle",a[0])[0];l.remove(d,"hidden");l.add(c,"hidden");c=20;c=0<b.length?c+35:c+10;p.set(a,"width","calc(100% - "+c+"px)")},getRelatedRecordsCount:function(b,c){var a,d,e;d=this.parentFeature._layer;e=this.parentFeature.attributes[this.parentFeature._layer.objectIdField];a=new y;c=this.layerInfosObj.getLayerOrTableInfoById(c).layerObject.objectIdField;a.returnGeometry=!1;a.outSpatialReference=this.mapSpatialReference;a.relationshipId=b;a.objectIds=[e];a.outFields=[c];this._showLoadingIndicator(b);
d.queryRelatedFeatures(a,g.hitch(this,function(a){(a=a[e]&&a[e].features)?this.displayRelatedRecordCount(a.length,b):this.displayRelatedRecordCount(0,b)}),g.hitch(this,function(){this.displayRelatedRecordCount(0,b)}))}})});