// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/on dojo/query dijit/registry jimu/filterUtils jimu/BaseWidgetSetting".split(" "),function(p,q,n,f,c,r,l,t,u,v){return q([v],{_attrInspector:null,_fieldValidation:null,_feature:null,_fieldInfo:null,_gdbRequiredFields:null,_notEditableFields:null,_fieldNameToAlias:null,_fieldsWithRules:null,_attTable:null,_filterUtils:null,_mapLayer:null,OPERATORS:null,constructor:function(){this.inherited(arguments);n.mixin(this,arguments[0]);
String.prototype.endsWith||(String.prototype.endsWith=function(b,a){if(void 0===a||a>this.length)a=this.length;return this.substring(a-b.length,a)===b});this.useFieldName=!1;this._mapLayer=this._feature.getLayer();this._attTable=l("td.atiLabel",this._attrInspector.domNode);if(0<this._attTable.length){var a=this._attTable[0];a&&a.hasAttribute("data-fieldname")&&(this.useFieldName=!0)}this._processLayer();this._filterUtils=new u;this.OPERATORS=n.clone(this._filterUtils.OPERATORS);void 0!==this._attTable&&
null!==this._attTable&&this._bindEvents()},_processLayer:function(){this._gdbRequiredFields=[];this._notEditableFields=[];this._fieldsWithRules=[];f.forEach(this._fieldInfo,function(a){var b;!0===this.useFieldName?b=a.fieldName:(b=a.label,0<=b.indexOf('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e')&&(b=b.replace('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e',"")));!1===a.nullable&&!0===a.isEditable&&this._gdbRequiredFields.push(b);!1!==a.isEditable&&!1!==a.isEditableSettingInWebmap||this._notEditableFields.push(b);
this._fieldValidation&&this._fieldValidation.hasOwnProperty(a.fieldName)&&this._fieldsWithRules.push(b)},this)},toggleFields:function(a){a="undefined"!==typeof a&&null!==a?a:!0;if(void 0!==this._attTable&&null!==this._attTable&&void 0!==this._fieldValidation&&null!==this._fieldValidation&&void 0!==this._feature&&null!==this._feature){var b=null,d=[],c;f.forEach(this._fieldInfo,n.hitch(this,function(e){var g;!0===this.useFieldName?g=e.fieldName:(g=e.label,0<=g.indexOf('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e')&&
(g=g.replace('\x3ca class\x3d"asteriskIndicator"\x3e *\x3c/a\x3e',"")));b=null;c=this.validateField(e.fieldName);b=c[1];!1===c[2]&&d.push({fieldName:e.fieldName});!0===c[0]&&this.toggleFieldOnAttributeInspector(g,b,c[2],a)}));return d}},validateField:function(a){var b=null;if(this._fieldValidation.hasOwnProperty(a)){if(0===this._fieldValidation[a].length)return[!1,null,!0];var d=[!1,null,null];f.some(this._fieldValidation[a],function(c){if(void 0!==c.filter&&null!==c.filter&&(b=c.filter,d=[!0,null,
null],this.processFilter(b,this._feature)))return"Required"===c.actionName?!1===this._feature.attributes.hasOwnProperty(a)?(d=[!0,c.actionName,!1],!0):null===this._feature.attributes[a]||""===this._feature.attributes[a]?(d=[!0,c.actionName,!1],!0):this.myIsNaN(this._feature.attributes[a])?(d=[!0,c.actionName,!1],!0):(d=[!0,c.actionName,!0],!0):(d=[!0,c.actionName,null,c.submitWhenHidden],!0)},this);return d}return[!1,null,null]},_bindEvents:function(){void 0!==this._attTable&&null!==this._attTable&&
0<this._attTable.length&&f.forEach(this._attTable,function(a){a=this._getRowInfo(a);-1!==this._fieldsWithRules.indexOf(a[3])&&"dijit.form.FilteringSelect"===a[2].declaredClass&&r(a[2],"change",n.hitch(this,this._smartComboValidate()))},this)},processFilter:function(a){var b=[];f.forEach(a.parts,function(a){if(a.hasOwnProperty("parts"))b.push(this.processFilter(a,this._feature));else{var d=null,c=null;a.valueObj.hasOwnProperty("value")&&(d=a.valueObj.value);a.valueObj.hasOwnProperty("value1")&&(d=
a.valueObj.value1);a.valueObj.hasOwnProperty("value2")&&(c=a.valueObj.value2);switch(a.valueObj.type){case "value":b.push(this.validatePart(a.operator,this._feature.attributes[a.fieldObj.name],d,c,a.caseSensitive));break;case "unique":b.push(this.validatePart(a.operator,this._feature.attributes[a.fieldObj.name],d,c,a.caseSensitive));break;case "field":this._feature.attributes.hasOwnProperty(d)&&(d=this._feature.attributes[d]),b.push(this.validatePart(a.operator,this._feature.attributes[a.fieldObj.name],
d,c,a.caseSensitive))}}},this);return this.ruleValid(b,a.logicalOperator)},ruleValid:function(a,b){var d=!1;if(void 0===b||null===b)b="OR";f.some(a,function(a){if("OR"===b){if(!0===a)return d=!0;d=!1}else{if(!1===a)return d=!1,!0;d=!0}});return d},myIsNaN:function(a){return a!==a},_isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},validatePart:function(a,b,d,c,g){var e=null;if(void 0===a||null===a)return!1;0===a.lastIndexOf("string",0)?!1===g&&(void 0!==b&&null!==b&&(b=String(b).toUpperCase()),
void 0!==d&&null!==d&&(d=String(d).toUpperCase()),void 0!==c&&null!==c&&(c=String(c).toUpperCase())):0===a.lastIndexOf("date",0)&&(void 0!==d&&null!==d&&(d=new Date(d)),void 0!==c&&null!==c&&(c=new Date(c)));switch(a){case this.OPERATORS.stringOperatorIs:if(b===d)return!0;break;case this.OPERATORS.stringOperatorIsNot:if(b!==d)return!0;break;case this.OPERATORS.stringOperatorStartsWith:if(null===b&&null===d)return!0;if(null===b&&null!==d)break;if(null!==b&&null===d)break;if(0===b.lastIndexOf(d,0))return!0;
break;case this.OPERATORS.stringOperatorEndsWith:if(null===b&&null===d)return!0;if(null===b&&null!==d)break;if(null!==b&&null===d)break;return b.endsWith(d);case this.OPERATORS.stringOperatorContains:if(null===b&&null===d)return!0;if(null===b&&null!==d)break;if(null!==b&&null===d)break;if(0<=String(b).toUpperCase().indexOf(d.toUpperCase()))return!0;break;case this.OPERATORS.stringOperatorDoesNotContain:if(null===b&&null===d)break;if(null===b&&null!==d||null!==b&&null===d||!(0<=String(b).toUpperCase().indexOf(d.toUpperCase())))return!0;
break;case this.OPERATORS.stringOperatorIsBlank:return void 0===b||null===b||""===b;case this.OPERATORS.stringOperatorIsNotBlank:return void 0!==b&&null!==b&&""!==b;case this.OPERATORS.numberOperatorIs:if(this._isNumeric(b))return String(b)===String(d);break;case this.OPERATORS.numberOperatorIsNot:if(this._isNumeric(b))return String(b)!==String(d);break;case this.OPERATORS.numberOperatorIsAtLeast:if(this._isNumeric(b)&&this._isNumeric(d))return Number(b)>=Number(d);break;case this.OPERATORS.numberOperatorIsLessThan:if(this._isNumeric(b)&&
this._isNumeric(d))return Number(b)<Number(d);break;case this.OPERATORS.numberOperatorIsAtMost:if(this._isNumeric(b)&&this._isNumeric(d))return Number(b)<=Number(d);break;case this.OPERATORS.numberOperatorIsGreaterThan:if(this._isNumeric(b)&&this._isNumeric(d))return Number(b)>Number(d);break;case this.OPERATORS.numberOperatorIsBetween:if(this._isNumeric(b)&&this._isNumeric(d)&&this._isNumeric(c))return Number(b)>Number(d)&&Number(b)<Number(c);break;case this.OPERATORS.numberOperatorIsNotBetween:if(this._isNumeric(b)&&
this._isNumeric(d)&&this._isNumeric(c))return Number(b)<=Number(d)||Number(b)>=Number(c);break;case this.OPERATORS.numberOperatorIsBlank:if(null===b||void 0===b||!1===this._isNumeric(b))return!0;break;case this.OPERATORS.numberOperatorIsNotBlank:if(null!==b&&void 0!==b&&!0===this._isNumeric(b))return!0;break;case this.OPERATORS.dateOperatorIsOn:if(void 0===b||null===b)break;if(void 0===d||null===d)break;e=new Date(b);return d.toDateString()===e.toDateString();case this.OPERATORS.dateOperatorIsNotOn:if(void 0===
b||null===b)break;if(void 0===d||null===d)break;e=new Date(b);return d.toDateString()!==e.toDateString();case this.OPERATORS.dateOperatorIsBefore:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b<d.getTime();case this.OPERATORS.dateOperatorIsAfter:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b>d.getTime();case this.OPERATORS.dateOperatorIsOnOrBefore:if(null===b||void 0===b)break;if(void 0===d||null===d)break;return b<d.getTime();case this.OPERATORS.dateOperatorIsOnOrAfter:if(null===
b||void 0===b)break;if(void 0===d||null===d)break;return b>d.getTime();case this.OPERATORS.dateOperatorIsBetween:if(null===b||void 0===b)break;if(void 0===d||null===d)break;if(void 0===c||null===c)break;return b>d.getTime()&&b<c.getTime();case this.OPERATORS.dateOperatorIsNotBetween:if(null===b||void 0===b)break;if(void 0===d||null===d)break;if(void 0===c||null===c)break;return b<=d.getTime()||b>=c.getTime();case this.OPERATORS.dateOperatorIsBlank:if(null===b||void 0===b)return!0;break;case this.OPERATORS.dateOperatorIsNotBlank:if(null!==
b&&void 0!==b)return!0}return!1},_processChildNodes:function(a,b){a.disabled=b;!0===b?a.style&&(a.style.pointerEvents="none"):a.style&&(a.style.pointerEvents="auto");f.forEach(a.childNodes,function(a){a.disabled=b;!0===b?a.style&&(a.style.pointerEvents="none"):a.style&&(a.style.pointerEvents="auto");0<a.childNodes.length&&this._processChildNodes(a,b)},this)},_smartComboValidate:function(){this.toggleFields()},_getRowInfo:function(a){var b=a.parentNode.childNodes[1].childNodes[0],d=null;1<a.parentNode.childNodes[1].childNodes.length&&
(d=a.parentNode.childNodes[1].childNodes[1]);var c;c=!0===this.useFieldName?a.hasAttribute("data-fieldname")?a.getAttribute("data-fieldname"):a.childNodes[0].data:a.childNodes[0].data;a=a.parentNode;var g=t.getEnclosingWidget(b);return[b,a,g,c,d]},_removeRequireFieldMarkings:function(a,b,d){var e=null;void 0===d||null===d?(c.contains(a,"dijitComboBoxError")&&c.remove(a,"dijitComboBoxError"),c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&
c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=l(".dijitValidationContainer",b),f.forEach(e,function(a){a.parentNode.removeChild(a)})):(e=n.isFunction(d.isValid)?d.isValid():!0,"dijit.form.TextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),
c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=l(".dijitValidationContainer",b),f.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.ValidationTextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitTextBoxDisabled")&&c.remove(a,"dijitTextBoxDisabled"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),
c.contains(a,"dijitError")&&c.remove(a,"dijitError")):"dijit.form.DateTextBox"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=l(".dijitValidationContainer",b),f.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.TimeTextBox"===
d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=l(".dijitValidationContainer",b),f.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.FilteringSelect"===d.declaredClass&&!0===e?(c.contains(a,"dijitTextBoxError")&&c.remove(a,
"dijitTextBoxError"),c.contains(a,"dijitComboBoxError")&&c.remove(a,"dijitComboBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,"dijitValidationTextBoxError")):!0===e&&(c.contains(a,"dijitComboBoxError")&&c.remove(a,"dijitComboBoxError"),c.contains(a,"dijitTextBoxError")&&c.remove(a,"dijitTextBoxError"),c.contains(a,"dijitValidationTextBox")&&c.remove(a,"dijitValidationTextBox"),c.contains(a,"dijitValidationTextBoxError")&&c.remove(a,
"dijitValidationTextBoxError"),c.contains(a,"dijitError")&&c.remove(a,"dijitError"),e=l(".dijitValidationContainer",b),f.forEach(e,function(a){a.parentNode.removeChild(a)})))},_removeRedAst:function(a,b){-1===this._gdbRequiredFields.indexOf(b)&&(a=l("a.asteriskIndicator",a),0<a.length&&f.forEach(a,function(a){a.parentNode.removeChild(a)}))},_removeHideRule:function(a){c.contains(a,"hideField")&&c.remove(a,"hideField")},_removeDisableRule:function(a,b){-1===this._notEditableFields.indexOf(a)&&(c.contains(b,
"dijitTextBoxDisabled")&&c.remove(b,"dijitTextBoxDisabled"),c.contains(b,"dijitComboBoxDisabled")&&c.remove(b,"dijitComboBoxDisabled"),c.contains(b,"dijitValidationTextBoxDisabled")&&c.remove(b,"dijitValidationTextBoxDisabled"),c.contains(b,"dijitDisabled")&&c.remove(b,"dijitDisabled"));this._processChildNodes(b,!1)},_remove:function(a,b,c,e,g){this._removeRequireFieldMarkings(c,e,g);this._removeRedAst(a[0],b);this._removeDisableRule(b,c);this._removeHideRule(e)},toggleFieldOnAttributeInspector:function(a,
b,d,e){e="undefined"!==typeof e&&null!==e?e:!0;if(void 0===this._gdbRequiredFields||null===this._gdbRequiredFields)this._gdbRequiredFields=[];if(void 0===this._notEditableFields||null===this._notEditableFields)this._notEditableFields=[];if(void 0!==this._attTable&&null!==this._attTable&&0<this._attTable.length){var g=p.filter(this._attTable,n.hitch(this,function(b){return b.childNodes&&0<b.childNodes.length?!0===this.useFieldName?b.hasAttribute("data-fieldname")?b.getAttribute("data-fieldname")===
a:b.childNodes[0].data===a:b.childNodes[0].data===a:!1})),f=null;if(null!==g&&0<g.length){var k=this._getRowInfo(g[0]),h=k[0],f=k[4],m=k[1],k=k[2];if(void 0!==k&&null!==k)switch(b){case "Hide":this._removeRequireFieldMarkings(h,m,k);this._removeRedAst(g[0],a);this._removeDisableRule(a,h);c.add(m,"hideField");break;case "Disabled":this._removeRedAst(g[0],a);this._removeHideRule(m);this._removeRequireFieldMarkings(h,m,k);c.add(h,["dijitValidationTextBox","dijitTextBoxDisabled","dijitComboBoxDisabled",
"dijitValidationTextBoxDisabled","dijitDisabled"]);this._processChildNodes(h,!0);null!==f&&(this._removeRequireFieldMarkings(f,m,k),c.add(f,["dijitValidationTextBox","dijitTextBoxDisabled","dijitComboBoxDisabled","dijitValidationTextBoxDisabled","dijitDisabled"]),this._processChildNodes(f,!0));break;case "Required":this._removeDisableRule(a,h);this._removeHideRule(m);!0===d?this._removeRequireFieldMarkings(h,m,k):"dijit.form.TextBox"===k.declaredClass?(f=l(".dijitValidationContainer",m),0===f.length&&
(b=document.createElement("div"),b.setAttribute("class","dijitReset dijitValidationContainer"),d=document.createElement("input"),d.setAttribute("class","dijitReset dijitInputField dijitValidationIcon dijitValidationInner"),d.setAttribute("value","x"),d.setAttribute("type","text"),d.setAttribute("tabindex","-1"),d.setAttribute("readonly","readonly"),d.setAttribute("role","presentation"),b.appendChild(d),h.insertBefore(b,h.childNodes[0])),c.add(h,["dijitTextBoxError","dijitValidationTextBox","dijitValidationTextBoxError",
"dijitError"])):"dijit.form.ValidationTextBox"===k.declaredClass?(f=l(".dijitValidationContainer",m),c.add(h,["dijitTextBoxError","dijitValidationTextBox","dijitValidationTextBoxError","dijitError"])):"dijit.form.FilteringSelect"===k.declaredClass?c.add(h,["dijitTextBoxError","dijitComboBoxError","dijitError","dijitValidationTextBoxError"]):c.add(h,["dijitTextBoxError","dijitError"]);h=l("a.asteriskIndicator",g[0]);b=l("span.atiRequiredField",g[0]);-1===this._gdbRequiredFields.indexOf(a)&&0===h.length&&
0===b.length&&(h=document.createElement("a"),h.setAttribute("class","asteriskIndicator"),h.innerHTML=" *",g[0].appendChild(h));break;case "Value":break;default:e&&this._remove(g,a,h,m,k)}}}}})});